name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml:
          - stack.yaml
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@main
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@main
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
